package com.app.crypto;

import static com.codename1.ui.CN.*;

import com.app.crypto.controllers.CryptoController;
import com.codename1.l10n.L10NManager;
import com.codename1.rad.controllers.ApplicationController;
import com.codename1.rad.controllers.ControllerEvent;
import com.codename1.rad.nodes.ViewNode;
import com.codename1.ui.plaf.UIManager;

import java.io.IOException;
import java.util.Hashtable;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class crypto extends ApplicationController {
    private static Form current = null;
    private Resources theme;
    private static boolean darkMode = false;

    // ============== 核心：只启动 CryptoView ==============
    @Override
    public void actionPerformed(ControllerEvent evt) {
        if (evt instanceof StartEvent) {
            evt.consume();
            // 创建基础视图节点
            ViewNode viewNode = new ViewNode();

            // ✅ 直接显示你的加解密界面
            new CryptoController(this, viewNode).getView().show();
        }
    }

    // ============== 保留必要的主题初始化 ==============
    private void initTheme() {
        String themeFileName = darkMode ? "/dark-theme" : "/theme";
        try {
            Resources theme = Resources.openLayered(themeFileName);
            UIManager.getInstance().addThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
        } catch(IOException e){
            Log.e(e);
        }
        Form currForm = Display.getInstance().getCurrent();
        if (currForm != null) currForm.refreshTheme();
    }

    // ============== 保留框架必需的生命周期方法 ==============
    @Override
    public void init(Object context) {
        try {
            theme = Resources.openLayered("/theme");
            UIManager.getInstance().setThemeProps(theme.getTheme(theme.getThemeResourceNames()[0]));
            Resources.setGlobalResources(theme);
        } catch(IOException e){
            Log.e(e);
        }
        Toolbar.setGlobalToolbar(true);
        Log.bindCrashProtection(true);
        updateNetworkThreadCount(2);
        dispatchEvent(new InitEvent(context));
    }

    @Override
    public void stop() {
        current = getCurrentForm();
        dispatchEvent(new StopEvent());
    }

    @Override
    public void start() {
        showCurrentForm();
        if (current == null) dispatchEvent(new StartEvent());
    }

    @Override
    protected void showCurrentForm() {
        if (current != null) current.show();
    }

    public static boolean isDarkMode(){ return darkMode; }
}
