#Updated keystore
#Thu Apr 16 18:30:34 CST 2026
codename1.android.keystore=D\:\\workspace_java\\crypto\\android\\..\\common\\androidCerts\\KeyChain.ks
codename1.android.keystoreAlias=androidKey
codename1.android.keystorePassword=password
codename1.arg.ios.newStorageLocation=true
codename1.arg.java.version=8
codename1.autoUpdate=false
codename1.cssTheme=true
codename1.disableUpdate=true
codename1.displayName=crypto
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.com.app.crypto
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.mainName=crypto
codename1.packageName=com.app.crypto
codename1.secondaryTitle=Hello World
codename1.vendor=CodenameOne
codename1.version=1.0
